- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
Added SupportShouldProcess to Stop-GcSqlReplica, Restore-GcSqlInstanceBackup cmdlets after looking at documentation which suggested these might result in some setting/data/process deletion. (Also fixed a couple comment issues in Restore-GcSqlInstanceBackup.)
> Added SupportShouldProcess to Stop-GcSqlReplica, Restore-GcSqlInstanceBackup cmdlets

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsBucketWebsite.Tests.ps1
- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsObject.cs
This PR adds a new `Set-GcsObject` cmdlet that allows you to update the metadata of an object. Currently the only operation is that it will allow you to specify a default ACL (e.g. "publicRead".)
In addition the PR changes the project for a few API calls, previously we had the default behavior where the API would return the object without the ACL information. This leads to confusion since it looks like objects have no ACLs at all, when in reality they do.
I'll log some issues (assigned to me) to continue fleshing out ACL-support in GCS. Specifically some integration tests for default object ACLs on buckets, and that they work correctly. Also, the ability to read/write object metadata as key/value pairs.
> Add Set-GcsObject cmdlet

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsObject.cs
Folded into this is a fix for making Write-GcsObject write zero bytes correctly. This fixes issue #127.
> Make Read-GcsObject take an input object from the pipeline.

- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlInstances.Tests.ps1
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
Make SettingsVersion parameter mandatory in Failover-GcSqlInstance cmdlet. For consistency with API and other cmdlets.
> Make SettingsVersion parameter mandatory in Failover-GcSqlInstance cmdlet

- Tools/CheckCmdletXmlDocs.psm1
- gcloud-powershell.sln
Have the Cmdlet Doc Checker take in a whitelist for cmdlets that don't have/need an OutputType attribute (e.g., cmdlets that don't output any objects). Also, 	change order of helper functions in Cmdlet Doc checker to more logically follow the order the functions are called.
> Add OutputType whitelist for Cmdlet Doc Checker

- Tools/CheckCmdletXmlDocs.psm1
Add check in CheckCmdletXmlDocs to ensure that all parameters have a valid (non-null, non-whitespace) description. Fix spacing and add deleted return statement as well.
> CheckCmdletXmlDocs: Ensure parameters have descriptions, fix 1 spacing, 1 missing return. 

- Google.PowerShell.IntegrationTests/Dns/Dns.GcdChange.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdManagedZone.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdQuota.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdResourceRecordSet.Tests.ps1
- Google.PowerShell/Dns/GcdManagedZone.cs
- Google.PowerShell/Dns/GcdQuota.cs
- Tools/CheckCmdletXmlDocs.psm1
- Tools/OutputTypeWhitelist.txt
- Change Dns Pester tests to use positional parameters to make sure they work when not directly named.
- Get-GcdQuota: Make the Project parameter optional but positional since it's the only parameter for the cmdlet. Add associated test. 
- Bring CheckCmdletXmlDocs up to its latest version in the master. 
- Add Remove-GcdManagedZone cmdlet to the OutputTypeWhitelist.txt file.
> Add positional parameter testing to DNS Pester tests and bring CmdletChecker up to date

- Google.PowerShell.IntegrationTests/Compute/Compute.GceInstance.Tests.ps1
- Google.PowerShell/Common/GcloudAttributes.cs
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
Adding this attribute allows -RemoveDisk to take a disk object, as well as a string name.
> Make Set-GceInstance -RemoveDisk take a Disk object.

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell.Tests/app.config
- Google.PowerShell.Tests/packages.config
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Storage/GcsBucket.cs
- Google.PowerShell/Storage/GcsBucketLogging.cs
- Google.PowerShell/Storage/GcsBucketWebsite.cs
- Google.PowerShell/Storage/GcsCmdlet.cs
- Google.PowerShell/Storage/GcsObject.cs
- Google.PowerShell/app.config
- Google.PowerShell/packages.config
This PR adds the ability to write/update GCS object metadata in the `New-GcsObject` and `Write-GcsObject` cmdlets. (You were always able to read it.)
This PR was a huge PITA because the GCS API has two places you can specify the `ContentType` for an object. So extra work is done to make sure that we always prefer the content type you specify via the parameter, and ignore the value from metadata if there is a conflict.
Also, PowerShell dictionaries are of the `Hashtable` which are subtltey different than the type we use internally, `Dictionary<string, string>`, and what the API expects, `IDictionary<string, string>`. However, a few convenience methods were able to blur those lines sufficiently.
This PR also updates the NuGet package versions. Pester was not able to run the tests until the …
> Enable reading/writing GCS object metadata

- Tools/CheckCmdletXmlDocs.psm1
CheckCmdletXmlDocs.psm1: Only print failing cmdlets and their associated warnings to output when run.
> CheckCmdletXmlDocs: Only output failing cmdlets

- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/packages.config
Update Google.Apis.Dns.v1 to version 1.15 for consistency with other packages. Will throw errors when running Dns cmdlets otherwise.
> Update Google.Apis.Dns.v1 to version 1.15

- website/content/home.html
Especially with three full-fixed-width spaces in the name, putting it in `<code>` looks totally awkward. In any case, `<code>` should be reserved for things you will actually type at the command line, which you never do with "Cloud Tools for PowerShell", unlike `gcloud` or even `Add-GcdManagedZone`.
Also rewords text with an incorrect use of "latter" in the last paragraph. It seems "later" was meant, but even then it was in need of  more extensive restructuring for English grammar and clarity.
> Drop code-font on "Cloud Tools for PowerShell"

- Tools/GenerateWebsiteData.ps1
Add Cloud DNS to GenerateWebsiteData.ps1 to add it to http://googlecloudplatform.github.io/google-cloud-powershell/cmdlets/.
> Add Cloud DNS to GenerateWebsiteData.ps1

- website/_data/products.json
- website/content/home.html
I work as part of this team at Google (alexdupuy@).
This is needed for it to appear in the left navbar of the Reference tab, and with a link to the Cmdlet examples in the website.
There are other problems that this doesn't fix, in particular, the Cloud DNS cmdlets page https://googlecloudplatform.github.io/google-cloud-powershell/cmdlets/google-cloud-dns.html gets a 404, although the dns-cmdlets branch was merged. I don't see the file(s) in the latest merge to website from master PR#275 either, so that also needs to be regenerated with the Cloud DNS docs (probably after merging PR#274) but other action may be needed.
> Add missing Google Cloud DNS to products.json & home.html

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsBucket.Tests.ps1
- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Storage/GcsObject.cs
Add -Folder parameter to New-GCSObject cmdlet to allow uploading of folder;
Use Cmdlet.GetResolvedProviderPathFromPSPath to resolve relative paths;
Instead of using -Path to combine File and Folder, I decided to add -Folder since there are certain parameters that can be applied to -File but not -Folder (like -ObjectName and -ContentType) and so it makes more sense to separate them into 2 different parameter sets.
> Add ability to upload folder to New-GCSObject

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsObject.cs
When uploading a file, we can use the file's name as the default for ObjectName instead of making the parameter mandatory. Fixes #94.
Also tweaks some documentation values. (e.g. "UploadFolder" is a more descriptive parameter set name than "ContentsFromFolder" IMHO.)
> Make New-GcsObject's -ObjectName parameter optional when uploading a file

- Tools/ArchiveCmdlets/ArchiveResources.psd1
- Tools/ArchiveCmdlets/LICENSE.txt
- Tools/ArchiveCmdlets/Microsoft.PowerShell.Archive.psd1
- Tools/ArchiveCmdlets/Microsoft.PowerShell.Archive.psm1
- Tools/BuildAndPackage.ps1
Context:
If the folder structure is something like "PowerShell\GoogleCloud\1.0.0.0\<Files>", then Compress-Archive will create an empty "PowerShell\GoogleCloud" folder in the ZipArchive. This causes a lot of test failures when we submit to the GoogleCloudSDK.
So in this PR, I first copied the Compress-Archive cmdlets from PowerShell repository and then change the cmdlet so that it will not create the empty folder.
The first commit is just copying the code from PowerShell repository. All the changes are made in the second commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/387)
> Update BuildAndPackage script to compress archive correctly

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Message.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Subscription.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Topic.Tests.ps1
- Google.PowerShell/PubSub/GcpsMessage.cs
- Google.PowerShell/PubSub/GcpsSubscription.cs
- Google.PowerShell/PubSub/GcpsTopic.cs
This allows us to pass Subscription and Topic objects to cmdlets more easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/408)
> Use Transformation Attribute in PubSub cmdlets

- Google.PowerShell.IntegrationTests/Compute/Compute.GceFirewall.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute/Compute.GceInstance.Tests.ps1
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
This is because we are using the Name property from the Disk object. However, this property gives us the persistent name of the Disk whereas what we need is the DeviceName of the disk (what the VM sees the Disk as).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/411)
> Fix a bug where -RemoveDisk in Set-GceInstance cmdlet does not work with Disk object

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Storage/GcsObject.cs
With this change, New-GcsObject will try to get the context of the current PowerShell location if it is inside a Google Cloud Storage Provider location. The cmdlet can then automatically fill out -Bucket as well as apply prefix to the object created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/428)
> Add integration between New-GcsObject and the provider

- Google.PowerShell/Common/ActiveUserConfig.cs
This is to address https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/440)
> Fix a bug where the initialization throws error when sentinel file does not exist.

- Google.PowerShell/ReleaseFiles/GoogleCloud.psd1
- Google.PowerShell/ReleaseFiles/GoogleCloudPowerShell.psd1
- Google.PowerShell/ReleaseFiles/GoogleCloudPowerShell.psm1
If user has the module without the Cloud SDK installed, the module will proceed to install the SDK. This scenario is needed when we publish the module to the PowerShell Gallery without the SDK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/451)
> Add the ability to download gcloud SDK

- Google.PowerShell/ReleaseFiles/GoogleCloudPlatform.Format.ps1xml
Also, separate the format for bucket and object (because bucket does not have ContentType and Size properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/452)
> Fix formating for get-gceinstance

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqDataset.Tests.ps1
- Google.PowerShell/BigQuery/GcbqDataset.cs
@ILMTitan - Here's the promised other PR to focus in on that Database issue.  
Context from last PR:
Consider:
```
gcloud config set core/project your-project
$whatTables = Get-BqDataset -Project "my-project" | Get-BqTable
```
$whatTables will now contain Tables from "your-project" even though the command was piped in Datasets from "my-project". Users will find that very surprising. Instead, we need to have two parameter sets, one that takes a -Project [string] and a -DatasetId [string], and one that takes a -Dataset [DatasetReference], because DatasetReference has both project and datasetId
> Get-GcbqDataset fixes from past PR

- Google.PowerShell.IntegrationTests/Compute2/Compute.GceServiceAccount.Tests.ps1
- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell/CloudResourceManager/IamPolicyCmdlets.cs
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Compute/GceServiceAccountConfigCmdlets.cs
- Google.PowerShell/Container/GkeClusterCmdlets.cs
This cmdlet creates a Google Container NodeConfig object. This object will be used in the cmdlet New-GkeContainerCluster (to be created after this) to configure nodes in a container cluster.
Also enable New-GceServiceAccountConfig to use the project's [default service account](https://cloud.google.com/compute/docs/access/service-accounts#compute_engine_default_service_account) when service account email is not provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/497)
> Add New-GkeNodeConfig cmdlet

- Google.PowerShell/Dns/GcdResourceRecordSet.cs
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
Also, prevent Get-ChildItem from throwing error for erroneous project for PowerShell Cloud Storage Provider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/500)
> Fix a bug where Get-GcdResourceRecordSet is not paging through the results.

- Tools/GenerateWebsiteData.ps1
Previously, we are comparing ParameterSets from Get-Help and Get-Command to update the syntax object we received from Get-Help (this syntax object does not have ParameterSets information). This can be pretty buggy (especially when there are dynamic parameters involved since the syntax object returned by Get-Help is not very accurate when these are present) so I added code to clean up the script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/526)
> Fix GenerateWebsiteData script not working with dynamic parameters

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTable.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTableRow.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
Remove -OutputVersionFormat as V1 LogSink is deprecated (this cmdlet is still in beta).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/529)
> Fix tests failure and remove -OutputVersionFormat from LogSink cmdlet

- Google.PowerShell/ReleaseFiles/GoogleCloud.psm1
This is to address https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/534.
With this fix, user will be able to install Cloud SDK non-interactively by default (as long as they keep selecting "Yes" or just "Yes To All" when prompted).
The fix also improves the progress bar experience (removes the progress bar from Invoke-WebRequest and add our own).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/538)
> Improve Cloud SDK installation experience

- Google.PowerShell.IntegrationTests/Provider/Storage.Provider.Tests.ps1
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/ReleaseFiles/GoogleCloud.psd1
- Google.PowerShell/ReleaseFiles/GoogleCloud.psm1
This lets the user change the directory to gs:\ before loading the module (and therefore the provider).
> Adds the gs:() function.

- Google.PowerShell.DotnetCore/Google.PowerShell.DotnetCore.csproj
- Nuget.config
The Dotnet core project was failing for me because of NuGet package issues. Add a new NuGet.Config at the solution root. Also, change the way the project imports the files to be less verbose.
> Fix .Net Core build.

- Google.PowerShell/Common/CloudSdkSettings.cs
- Google.PowerShell/Common/GcloudWrapper.cs
- Google.PowerShell/Compute/GceSnapshotCmdlets.cs
- Google.PowerShell/ReleaseFiles/GoogleCloud.psm1
- Tools/BuildAndPackage.ps1
After this change, the `.\BuildAndPackage.ps1` script will package both the Core CLR and normal CLR bits into one module. The `GoogleCloud.psm1` file will pick which assembly to load based on the PowerShell runtime. This way, our module will work across the different platforms.
I also added logic to install Cloud SDK on Unix systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/571)
> Change tooling to package .NET Core module

- Google.PowerShell/ReleaseFiles/BootstrapCloudToolsForPowerShell.ps1
- Tools/BuildAndPackage.ps1
The issue is that the "Cloud Tools For PowerShell" application is looking for "BootstrapCloudToolsForPowerShell.ps1" at the wrong place. Also, the bootstrap script itself is importing the module with the wrong directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/596)
> Fix a bug where BootstrapCloudToolsForPowershell is not found by Cloud Tools For PowerShell app

- Google.PowerShell.Tests/Compute/GceMetadataTests.cs
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell/Compute/GceMetadataCmdlet.cs
The bug happens because we keep adding headers to the `DefaultRequestHeaders` of a static `HttpClient`. This means that by the second time this is called, the header will be something like `"Metadata-Flavor" = {"Google", "Google" }` instead of `"Metadata-Flavor" = "Google"`.
> Fix a bug where Get-GceMetadata fails when called the second times

- Google.PowerShell.IntegrationTests/Dns/Dns.GcdChange.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdManagedZone.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdQuota.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdResourceRecordSet.Tests.ps1
- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsCmdlet.cs
- Google.PowerShell/Storage/GcsObject.cs
This should fix https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/626. See [link](https://cloud.google.com/storage/docs/metadata#mutable) for more information on fixed-key metadata.
Also fixes minor test errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/627)
> Fix a bug where fixed type metadata is not handled properly in GCS Object cmdlets.
