- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlSslCerts.Tests.ps1
- Google.PowerShell/Sql/GcSqlCmdlet.cs
- Google.PowerShell/Sql/GcSqlSslCmdlets.cs
The cmdlet and tests for Reset-GcSqlSslConfig
> Reset-GcSqlSslConfig

- Google.PowerShell/Dns/GcdChange.cs
- Google.PowerShell/Dns/GcdManagedZone.cs
- Google.PowerShell/Dns/GcdQuota.cs
- Google.PowerShell/Dns/GcdResourceRecordSet.cs
Rename DnsProject parameter to Project in dns cmdlets.
> Rename DnsProject parameter to Project.

- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlInstances.Tests.ps1
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Sql/GcSqlCmdlet.cs
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
Add Failover-GcSqlInstance cmdlet and associated tests.
> Add Failover-GcSqlInstance cmdlet

- Google.PowerShell.IntegrationTests/Compute/Compute.GceInstance.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute/Compute.GceInstanceTemplate.Tests.ps1
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
- Google.PowerShell/Compute/GceInstanceConfigCmdlets.cs
- Google.PowerShell/Compute/GceInstanceTemplateCmdlets.cs
As part of issue #99, make the machine type default to n1-standard-1.
> Default machine type

- Google.PowerShell/ReleaseFiles/AppendPsModulePath.ps1
Test-IsElevated is part of a gwindow module, not standard powershell. This replaces it with its definition.
> Remove Test-IsElevated

- Google.PowerShell/Storage/GcsObject.cs
Fixes issue #180. I cleaned up all the projections for GET requests, but missed LIST.
> Set full projection for LIST request in Find-GcsObject.

- Google.PowerShell/Sql/GcSqlBackupRunCmdlets.cs
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
- Google.PowerShell/Sql/GcSqlInstanceConfigCmdlets.cs
The second big update to XML documentation. With this, most sql cmdlets should have correct and updated XML documentation.
> Updating documentation 2

- Tools/CheckCmdletXmlDocs.psm1
Cmdlet doc checker:  Write "PASSED" if no doc errors were found.
> Cmdlet doc checker:  Write "PASSED" if no doc errors were found.

- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlInstances.Tests.ps1
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
- Google.PowerShell/Sql/GcSqlInstanceConfigCmdlets.cs
- Google.PowerShell/Sql/GcSqlInstanceReplicaConfigCmdlet.cs
- Google.PowerShell/Sql/GcSqlSettingConfigCmdlet.cs
- Google.PowerShell/Sql/GcSqlSslCmdlets.cs
Finally tested creating a read replica instance.
Fixed some small issues in documentation.
Created the XML documentation for New-GcSqlInstanceReplicaConfig
> Replica testing

- cmdlets/index.html
- content/home.html
Fix a missing quote and a misspelled word.
> Pushing update

- Google.PowerShell/Storage/GcsBucket.cs
- Google.PowerShell/Storage/GcsBucketLogging.cs
- Google.PowerShell/Storage/GcsBucketWebsite.cs
- Google.PowerShell/Storage/GcsObject.cs
Add `OutputType` attributes to cmdlets and add examples.
> Fix doc bugs

- .gitignore
- .gitmodules
website/_site becomes its own repo of the gh-pages branch of GoogleCloudPlatform/google-cloud-powershell.
> Make website/_site be a submodule.

- Google.PowerShell/Compute/GceAddressCmdlets.cs
- Google.PowerShell/Compute/GceAttachedDiskConfigCmdlets.cs
- Google.PowerShell/Compute/GceDisk.cs
- Google.PowerShell/Compute/GceFirewallCmdlets.cs
- Google.PowerShell/Compute/GceFirewallProtocolCmdlet.cs
- Google.PowerShell/Compute/GceImageCmdlets.cs
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
- Google.PowerShell/Compute/GceInstanceConfigCmdlets.cs
- Google.PowerShell/Compute/GceInstanceTemplateCmdlets.cs
- Google.PowerShell/Compute/GceMachineType.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
- Google.PowerShell/Compute/GceNetworkCmdlets.cs
- Google.PowerShell/Compute/GceServiceAccountConfigCmdlets.cs
- Google.PowerShell/Compute/GceSnapshotCmdlets.cs
- Google.PowerShell/Storage/GcsBucket.cs
- Google.PowerShell/Storage/GcsObject.cs
Fix or add examples to most of the documentation.
> Fix documentation and add examples.

- Google.PowerShell.IntegrationTests/Compute/Compute.GceFirewall.Tests.ps1
- Google.PowerShell/Compute/GceFirewallCmdlets.cs
> Fix the way Remove-GceFirewall takes an object.

- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlBackupRuns.Tests.ps1
- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlInstances.Tests.ps1
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell.Tests/app.config
- Google.PowerShell.Tests/packages.config
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Sql/GcSqlBackupRunCmdlets.cs
- Google.PowerShell/Sql/GcSqlCmdlet.cs
- Google.PowerShell/Sql/GcSqlFlagsCmdlet.cs
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
- Google.PowerShell/Sql/GcSqlSslCmdlets.cs
- Google.PowerShell/app.config
- Google.PowerShell/packages.config
Good catch Jim, that would have been a big mistake.
Notes from the (wrong) pull request:
The primary meat of this pull request is added Verbose capability for most cmdlets. The "get" cmdlets don't have it because they are much quicker and don't really have any steps to them.
All cmdlets that take time now display some progress.
The "Fixed Import Tests" commit happened because the instances lost SUPER Privilege for some reason (update with the API?), so the files being imported had to be changed slightly.
> Various fixes

- Google.PowerShell/Sql/GcSqlCmdlet.cs
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
- Google.PowerShell/Sql/GcSqlSslCmdlets.cs
Only one cmdlet needed to have the positional parameter of InstanceObject changed. Everything else was fine.
> Various fixes 2

- website/cmdlets/index.html
I added and modified comments in the code examples
I changes the left hand links from anchor within the page to links to the appropriate ref while we wait for @marceloyuela 's goodness.
> proposed edits to docs main page

- .gitattributes
I thought I fixed this before, I was wrong.
Beyond this, I re-ran all the pester tests to make sure they passed. They did.
> Fixing very minor issue with public.pem line endings. 

- website/cmdlets/index.html
Add a cmdlet description and mini scenario to the website for Cloud DNS.
> Add Website Info

- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell/Google.PowerShell.csproj
Woops!
After this is going to be the PR to merge the sql-cmdlets branch into the master.
> Very minor merge conflict I missed before.

- Tools/GenerateWebsiteData.ps1
- website_v2/gcloud-powershell-website-v2/www/static/_data/cmdletsFull.json
- website_v2/gcloud-powershell-website-v2/www/static/app/main_controller.js
- website_v2/gcloud-powershell-website-v2/www/static/templates/cmdlet.html
Just the added information of (clickable) related links for cmdlets.
> Related links

- Tools/GenerateWebsiteData.ps1
- website_v2/gcloud-powershell-website-v2/www/static/_data/cmdletsFull.json
For some reason all links in the cmdlets start with ( and end with ), throwing off the linking of the website.
This PR fixes that.
> Fixed a bug in the related links.

- Tools/GenerateWebsiteData.ps1
- website_v2/gcloud-powershell-website-v2/www/static/_data/cmdletsFull.json
- website_v2/gcloud-powershell-website-v2/www/static/app/main_controller.js
- website_v2/gcloud-powershell-website-v2/www/static/templates/cmdlet.html
- website_v2/gcloud-powershell-website-v2/www/static/templates/parameter-table.html
Some style fixes and the addition of getProperty to the main controller (depreciating getParams).
> Various website fixes

- Google.PowerShell.IntegrationTests/Compute/Compute.GceDisk.Tests.ps1
- Google.PowerShell/Compute/GceDisk.cs
This is a fix for issue #260. This is a fix for behavior we don't want to encourage, so I am intentionally leaving it undocumented to external users.
> Add a net for people who accidently put GB behind the size of their disks.

- Tools/OutputTypeWhitelist.txt
Remove extra . from Promote-GcSqlReplica in OutputTypeWhitelist.txt
> Remove extra . in OutputTypeWhitelist.txt

- Google.PowerShell/Common/GcloudAttributes.cs
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
Apparently I didn't merge the provider with master properly, as a compile error occured after the merge. Here is a fix for that.
> Fix a compile error that snuck into master.

- Google.PowerShell/Storage/GcsObject.cs
Fixes issue #228. I'll review examples later.
> Update descriptions of New-GcsObject and Write-GcsObject to mention warnings

- Google.PowerShell.IntegrationTests/GcloudCmdlets.ps1
- Google.PowerShell.IntegrationTests/Provider/Storage.Provider.Tests.ps1
- Google.PowerShell/Provider/BucketModel.cs
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
Fix a performance issue with getting the buckets. (Issue #322).
Fix a navigation bug changing directory to an implied folder that ends with "/".
Fix a bug where an exception is thrown if an accessible project was no longer active.
> Fix two bugs and a perforamnce issue.

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Common/AnalyticsReporter.cs
- Google.PowerShell/Storage/GcsObject.cs
Change -Contents to -Value for GcsObject cmdlets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/346)
> Add ability to pipeline GcsObject to Write-GcsObject cmdlet

- Google.PowerShell/Properties/AssemblyInfo.cs
- Google.PowerShell/ReleaseFiles/GoogleCloud.psd1
- Tools/BuildAndPackage.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/354)
> Update changes for the 0.1.9 release

- Google.PowerShell/Common/AnalyticsReporter.cs
- Google.PowerShell/Common/ProcessUtils.cs
- Google.PowerShell/Common/ReportCmdletResults.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/357)
> Fix compilation error after rebasing from master

- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlInstances.Tests.ps1
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
- Tools/OutputTypeWhitelist.txt
Change Promote-GcSqlReplica to ConvertTo-GcSqlInstance.
Change Failover-GcSqlInstance to Invoke-GcSqlInstanceFailover.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/359)
> Remove unapproved verbs

- Google.PowerShell/Common/AnalyticsReporter.cs
See original PR on the VS side:
https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/pull/245/files
"Flipping the indexes for the custom dimensions. Now the right values should be reported."
> Fix a problem with the event flags

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsBucket.Tests.ps1
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
- Google.PowerShell/Storage/GcsBucket.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/365)
> Add support for additional storage classes

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsAcl.Tests.ps1
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Storage/GcsAcl.cs
Add cmdlets for adding, listing and removing ACLs for:
1. GCS Bucket
2. GCS Object
3. Default Object ACLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/368)
> Add Google Cloud Storage ACLs cmdlets

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsBucket.Tests.ps1
- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsBucket.cs
- Google.PowerShell/Storage/GcsObject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/376)
> Fix error messages when objects or buckets are not found.

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsObject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/377)
> Merge Find-GcsObject into Get-GcsObject; Fix error message for Remove-GcsObject when object not found

- Tools/BuildAndPackage.ps1
- Tools/GenerateWebsiteData.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/378)
> Add the ability to compile the bits with release config

- website/js/app/controllers/content-product.ng
This is from issue https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/380)
> Add quick start documentation to google cloud storage.

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsAcl.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/381)
> Add sleep to fix Pester test failure.

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell.Tests/app.config
- Google.PowerShell.Tests/packages.config
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Logging/GcLogCmdlet.cs
- Google.PowerShell/app.config
- Google.PowerShell/packages.config
- Tools/BetaCmdlets.ps1
Add support for filtering log by severity and resource type
Add documentation for gclogcmdlet
Add tests for Logging cmdlet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/383)
> Implement Get-GcLogEntry to get StackDriver Log Entries.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/384)
> Update README.md with the correct path.

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlet.cs
- Tools/BetaCmdlets.ps1
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/385)
> Add new-gclogentry and new-gclogmonitoredresource cmdlets

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlet.cs
- Tools/BetaCmdlets.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/389)
> Add remove-gclogentry cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Tests.ps1
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Logging/GcLogCmdlet.cs
- Google.PowerShell/PubSub/GcpsCmdlet.cs
- Google.PowerShell/PubSub/GcpsTopic.cs
- Google.PowerShell/packages.config
- Tools/BetaCmdlets.ps1
Add New-GcpsTopic, Get-GcpsTopic and Remove-GcpsTopic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/392)
> Add Google Cloud PubSub Topics cmdlets.

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Subscription.Tests.ps1
- Google.PowerShell/PubSub/GcpsSubscription.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/397)
> Add Get-GcpsSubscription

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Subscription.Tests.ps1
- Google.PowerShell/PubSub/GcpsSubscription.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/398)
> Add Set-GcpsSubscriptionConfig cmdlet

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Subscription.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Topic.Tests.ps1
- Google.PowerShell/PubSub/GcpsSubscription.cs
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/401)
> Add Remove-GcpsSubscription cmdlet

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Message.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Subscription.Tests.ps1
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/PubSub/GcpsMessage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/402)
> Add Publish-GcpsMessage to publish PubSub message to a topic.

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Message.Tests.ps1
- Google.PowerShell/PubSub/GcpsMessage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/403)
> Add Get-GcpsMessage

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Message.Tests.ps1
- Google.PowerShell/PubSub/GcpsMessage.cs
This cmdlet is used to send acknowledgement for messages pulled from a PubSub subscription.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/412)
> Add Send-GcpsAck cmdlet

- Google.PowerShell.IntegrationTests/PubSub/PubSub.Message.Tests.ps1
- Google.PowerShell/PubSub/GcpsMessage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/417)
> Add Set-GcpsAckDeadline cmdlet.

- Google.PowerShell.IntegrationTests/Compute/Compute.GceHealthCheck.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute/Compute.GceInstance.Tests.ps1
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
These parameters are used to turn on/off autodelete in the disks of the instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/416)
> Add -TurnOnAutoDeleteDisk and -TurnOffAutoDelete to Set-GceInstance

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlet.cs
Also factor out the logic for constructing filter so we can reuse it in other log cmdlets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/418)
> Change Get-GcLogEntry so -Filter will work with other parameters

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlet.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/419)
> Add Get-GcLog cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Logging/GcLogCmdlets.cs
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/420)
> Add Get-GcLogSink cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlets.cs
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/421)
> Add New-GcLogSink cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/427)
> Add Remove-GcLogSink cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/426)
> Add ability to remove multiple logs from remove-gclog

- Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1
- Google.PowerShell/Storage/GcsObject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/429)
> Update various GcsObject cmdlets so they can be usable with Google Cloud Storage Provider.

- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
- Google.PowerShell/Storage/GcsBucket.cs
- Google.PowerShell/Storage/GcsObject.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/432)
> Fix comments for PredefinedAcl

- Tools/GenerateWebsiteData.ps1
Dynamic Parameter is not generated for the website because they don't show up in Get-Help. They do, however, show up in Get-Command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/433)
> Fix an issue where dynamic parameter is not generated for website.

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogMetric.Tests.ps1
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Logging/GcLogCmdlets.cs
- Google.PowerShell/Logging/GcLogMetricCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/436)
> Add Get-GcLogMetric cmdlet

- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/437)
> Fix comment for writeridentity parameter

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogMetric.Tests.ps1
- Google.PowerShell/Logging/GcLogMetricCmdlets.cs
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/441)
> Add New-GcLogMetric cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogMetric.Tests.ps1
- Google.PowerShell/Logging/GcLogMetricCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/442)
> Add remove-gclogmetric cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogMetric.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlets.cs
- Google.PowerShell/Logging/GcLogMetricCmdlets.cs
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
- Google.PowerShell/PubSub/GcpsMessage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/443)
> Add Set-GcLogMetric cmdlet

- js/app/controllers/content-product.ng
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/446)
> Add Logging and PubSub documentation

- js/app/controllers/content-product.ng
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/448)
> Fix documentation for website

- Google.PowerShell.IntegrationTests/CloudResourceManager/CloudResourceManager.IamPolicy.Tests.ps1
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell/CloudResourceManager/CloudResourceManagerCmdlets.cs
- Google.PowerShell/CloudResourceManager/IamPolicyCmdlets.cs
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/ReleaseFiles/GoogleCloudPlatform.Format.ps1xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/460)
> Add Get-IamPolicy cmdlet.

- Google.PowerShell.IntegrationTests/Compute/Compute.GceFirewall.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute/Compute.GceInstance.Tests.ps1
- Google.PowerShell/Compute/GceCmdlet.cs
- Google.PowerShell/Compute/GceFirewallCmdlets.cs
- Google.PowerShell/Compute/GceInstanceDescriptionCmdlet.cs
This is to address https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/461)
> Add logic to construct network URI.

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqDataset.Tests.ps1
- Google.PowerShell/BigQuery/GcbqDataset.cs
- Google.PowerShell/BigQuery/GcbqProject.cs
- Google.PowerShell/Google.PowerShell.csproj
Impemented the cmdlet and testing.  Word of warning, I haven't written remove-dataset, so the datasets must be removed manually from the testing project in between runs of the integration testing.  
Specific request from this code review:  Look at the way I implemented the parameters for this cmdlet and let me know if I'm going in the wrong direction with this.
> New-GcbqDataset cmdlet implemented

- Google.PowerShell.IntegrationTests/CloudResourceManager/CloudResourceManager.IamPolicy.Tests.ps1
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell.Tests/app.config
- Google.PowerShell.Tests/packages.config
- Google.PowerShell/CloudResourceManager/IamPolicyCmdlets.cs
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
- Google.PowerShell/Storage/GcsAcl.cs
- Google.PowerShell/app.config
- Google.PowerShell/packages.config
- Tools/BetaCmdlets.ps1
Also update the nuget packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/464)
> Add Add-GcIamPolicyBinding cmdlet

- Google.PowerShell.IntegrationTests/Provider/Storage.Provider.Tests.ps1
- Google.PowerShell/Provider/BucketModel.cs
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
- Google.PowerShell/Storage/GcsObject.cs
Also, use path separator based on OS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/467)
> Add ShouldContinue for removing folder

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/GcbqCmdlets.ps1
- Google.PowerShell/BigQuery/GcbqDataset.cs
Final Dataset cmdlet.  Purposefully ignoring the "patch" vs "update" case because in the c# api, they're functionally the same.  Also streamlines UX.
> Get-GcbqDataset cmdlet PR

- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/468)
> Speed up Get-ChildItem in GcsProvider.

- Google.PowerShell.IntegrationTests/Compute/Compute.GceBackendService.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdChange.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdManagedZone.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdQuota.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdResourceRecordSet.Tests.ps1
- Google.PowerShell.IntegrationTests/SQL2/SQL.GcSqlInstances.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/469)
> Fix test failures

- Google.PowerShell/ReleaseFiles/GoogleCloudPowerShell.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/477)
> Add Cloud SDK license when installing with no prompt

- Google.PowerShell/ReleaseFiles/GoogleCloud.psd1
- Google.PowerShell/ReleaseFiles/GoogleCloudPowerShell.psd1
- Google.PowerShell/ReleaseFiles/GoogleCloudPowerShell.psm1
@chrsmith Do we have a URL to an icon for the module?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/478)
> Add PSData to module manifest; add a warning to remind user to run 'gcloud init' after installing the Cloud SDK

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqTable.Tests.ps1
- Google.PowerShell/BigQuery/GcbqDataset.cs
- Google.PowerShell/BigQuery/GcbqTable.cs
New cmdlet and tests, as well as a bunch of formatting fixes to dataset code and changing a parameter name to be consistent with documentation.
One area that I would like comments on - testing the -Expiration flag.  
Is there a better way to do that other than "set a table to expire 10 seconds from instantiation and wait 20 seconds after the call returns to check"?
> New-GcbqTable and formatting fixes

- Google.PowerShell/Compute/GceAttachedDiskConfigCmdlets.cs
- Google.PowerShell/PubSub/GcpsMessage.cs
- Google.PowerShell/Sql/GcSqlInstanceCmdlets.cs
A few of our examples had alignment issues.
> Fixed some example alignment issues.

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.GcbqTable.Tests.ps1
- Google.PowerShell/BigQuery/GcbqDataset.cs
- Google.PowerShell/BigQuery/GcbqTable.cs
Made changes to Remove-Dataset and Get-Table to convert them to the new pattern of input (where datasetreferences override dataset and project id's).  Most of this was just retooling the way parameters were taken and adding parameter sets.
Involved changing parameters, so I updated docs and tests as well.
> Convert remaining cmdlets

- Tools/GenerateWebsiteData.ps1
This is the other part of this [PR](https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/487) (the other PR is for the sub repository and this one for the main repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/488)
> Add GcIam and Gcpproject to productinfolookup

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTable.Tests.ps1
- Google.PowerShell/BigQuery/BqDataset.cs
- Google.PowerShell/BigQuery/BqTable.cs
Remove-BqTable cmdlet + integration tests.  
(also changed over a few Gcbq*'s to Bq*'s that I missed in the previous commit)
> remove-bqtable cmdlet & tests

- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeCmdlet.cs
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/packages.config
- Tools/BetaCmdlets.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/494)
> Add Get-GkeCluster cmdlet

- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Tools/BetaCmdlets.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/498)
> Add Add-GkeCluster cmdlet

- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeCmdlet.cs
- Tools/BetaCmdlets.ps1
Also refactor the code that writes progress record while waiting for a Container Operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/501)
> Add Remove-GkeCluster cmdlet.

- Google.PowerShell/Dns/GcdChange.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/502)
> Fix a bug where Get-GcdChange is not paging through request

- Google.PowerShell.IntegrationTests/Container/Container.GkeNodePool.Tests.ps1
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
- Google.PowerShell/Google.PowerShell.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/503)
> Add Get-GkeNodePool cmdlet

- Google.PowerShell.IntegrationTests/Compute2/Compute.GceServiceAccount.Tests.ps1
- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
Add another way to create GKE cluster (by supplying NodePool objects).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/505)
> Add NodePool logic to Add-gkecluster

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BqCmdlets.ps1
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/Google.PowerShell.csproj
First cmdlet for job functionality.  Does Lists and Gets.
Same general template as the other 3 sections.
> Get-Bqjob + tests

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell/BigQuery/BqCmdlet.cs
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/BigQuery/BqTabledata.cs
> The Big Query

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell/BigQuery/BqJob.cs
Pretty short commit.  Added to the Query tests instead of making a new section.
> Receive-BqJob + tests

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell/BigQuery/BqJob.cs
Last new cmdlet.  
Tests below.  It's kind of weak at the moment, but I will add more cases to make sure it works as I can do more types of job requests.
> Stop- + tests (last new cmdlet!)

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell/BigQuery/BqCmdlet.cs
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/BigQuery/BqTabledata.cs
Super long PR, but most of it is just *all* of the Load parameters and the tests.  
That's the rest of Start-BqJob, so it includes the -Load and -Extract functionality.
> Finished Start-BqJob + tests

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTable.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTabledata.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/classics_broken.json
- Google.PowerShell/BigQuery/BqDataset.cs
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/BigQuery/BqTable.cs
- Google.PowerShell/BigQuery/BqTabledata.cs
Not going to a review for this one because there's not much if any substantial code changes.  Most of that is in the next commit, which will be reviewed.
> Bqjob Docs fixes and other minor changes

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTable.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTableRows.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/schema.json
- Google.PowerShell.IntegrationTests/BigQuery/schema_mini.json
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell/BigQuery/BqCmdlet.cs
- Google.PowerShell/BigQuery/BqDataset.cs
- Google.PowerShell/BigQuery/BqTable.cs
- Google.PowerShell/BigQuery/BqTableRows.cs
- Google.PowerShell/Google.PowerShell.csproj
Set- should add on 404  (for databases and tables both)
Switch to Add-BqTableRows and Get-BqTableRows  (rename)
Schema builder from JSON string or file
Add schema to table creation with flag
(p2) Fix Add-TableRows: -Format [CSV|JSON] (reorder params to match job syntax)
> Code-heavy P1 bugs

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqDataset.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTable.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTableRow.Tests.ps1
- Google.PowerShell.IntegrationTests/BigQuery/BqCmdlets.ps1
- Google.PowerShell.IntegrationTests/Google.PowerShell.IntegrationTests.csproj
- Google.PowerShell/BigQuery/BqDataset.cs
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/BigQuery/BqTable.cs
- Google.PowerShell/BigQuery/BqTableRow.cs
- Google.PowerShell/Google.PowerShell.csproj
Again, a massive commit.  Lots of little fixes and text edits.  
Major feature to review is the Label flags in Get- and Set-BqDataset.  Tests are added too.
> p2 fixes + testing junk

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/525)
> Update README.md to include installation from PowerShell gallery.

- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell.IntegrationTests/Container/Container.GkeNodePool.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
Factor out a part of the Add-GkeCluster cmdlet to create GkeNodePoolConfigCmdlet abstract class, which is used to create New-GkeNodePool cmdlet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/527)
> Add New-GkeNodePool cmdlet

- Google.PowerShell.IntegrationTests/Dns/Dns.GcdChange.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdManagedZone.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdQuota.Tests.ps1
- Google.PowerShell.IntegrationTests/Dns/Dns.GcdResourceRecordSet.Tests.ps1
- Google.PowerShell.IntegrationTests/GcloudCmdlets.ps1
The main problem is we are not setting DISABLE_POWERSHELL_ANALYTICS before we import the module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/528)
> Fix bugs where tests reports too much information

- Google.PowerShell.IntegrationTests/Container/Container.GkeNodePool.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
- Tools/BetaCmdlets.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/530)
> Add Add-GkeNodePool cmdlet

- Google.PowerShell.IntegrationTests/Compute2/Compute.GceManagedInstanceGroup.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute2/Compute.GceTargetPool.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
Also remove -OutputVersionFormat tests since we removed that parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/531)
> Fix Pester tests failure

- Google.PowerShell.IntegrationTests/Container/Container.GkeNodePool.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/533)
> Add Remove-GkeNodePool cmdlet

- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell/CloudResourceManager/IamPolicyCmdlets.cs
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Container/GkeClusterCmdlets.cs
- Google.PowerShell/Container/GkeCmdlet.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
- Google.PowerShell/Logging/GcLogCmdlets.cs
- Tools/BetaCmdlets.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/535)
> Add Set-GkeCluster cmdlet to update Gke Cluster

- js/app/controllers/content-product.ng
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/539)
> Add documentation for Google Cloud Container Engine cmdlets

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/Container/Container.GkeCluster.Tests.ps1
- Google.PowerShell.IntegrationTests/Container2/Container.GkeNodePool.Tests.ps1
- Google.PowerShell/Compute/GceFirewallCmdlets.cs
- Google.PowerShell/Container/GkeCmdlet.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
- Google.PowerShell/Storage/GcsBucketLogging.cs
Also fix some test failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/543)
> Fix bugs for Remove-GkeNodePool

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell/BigQuery/BqJob.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/551)
> Add -MaxBadRecords parameter

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute2/Compute.GceNetwork.Tests.ps1
- Google.PowerShell.IntegrationTests/Compute2/Compute.GceRoute.Tests.ps1
- Google.PowerShell.IntegrationTests/Container2/Container.GkeNodePool.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Topic.Tests.ps1
- Google.PowerShell/Container/GkeClusterCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/552)
> Fix miscellaneous test failures

- Google.PowerShell.IntegrationTests/Compute2/Compute.GceNetwork.Tests.ps1
- Google.PowerShell/Compute/GceNetworkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/553)
> Add New-GceNetwork cmdlet

- Google.PowerShell.IntegrationTests/Compute2/Compute.GceNetwork.Tests.ps1
- Google.PowerShell/Compute/GceNetworkCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/554)
> Add Remove-GceNetwork cmdlet

- Google.PowerShell.IntegrationTests/Logging/Logging.GcLog.Tests.ps1
- Google.PowerShell.IntegrationTests/Logging/Logging.GcLogSink.Tests.ps1
- Google.PowerShell.IntegrationTests/PubSub/PubSub.Subscription.Tests.ps1
- Google.PowerShell.IntegrationTests/SQL/SQL.GcSqlReplicas.Tests.ps1
- Google.PowerShell/Logging/GcLogCmdlets.cs
- Google.PowerShell/Logging/GcLogSinkCmdlets.cs
There are some changes in the Logging API so we have to change some of the logging cmdlets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/558)
> Fix tests and update log cmdlets

- Google.PowerShell.DotnetCore/Google.PowerShell.DotnetCore.csproj
- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqTableRow.Tests.ps1
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell.Tests/app.config
- Google.PowerShell.Tests/packages.config
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/Container/GkeNodePoolCmdlets.cs
- Google.PowerShell/Google.PowerShell.csproj
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
- Google.PowerShell/app.config
- Google.PowerShell/packages.config
Also include `IamPolicyCmdlets` and `Container` cmdlets to .NET Core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/563)
> Update nuget package

- js/app/controllers/content-product.ng
> Change the documentation use of Find-GcsObject to Get-GcsObject.

- Google.PowerShell/ReleaseFiles/GoogleCloud.psm1
> Add "-quiet" parameter to Import-Module -ArgumentList

- Google.PowerShell.Tests/BigQuery/BqCmdletTestBase.cs
- Google.PowerShell.Tests/BigQuery/StartBqJobTests.cs
- Google.PowerShell.Tests/Compute/GceCmdletTestBase.cs
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell.Tests/Provider/GoogleCloudStorageProviderTests.cs
- Google.PowerShell.Tests/Storage/GcsCmdletTestBase.cs
- Google.PowerShell/BigQuery/BqCmdlet.cs
- Google.PowerShell/BigQuery/BqJob.cs
- Google.PowerShell/Compute/GceCmdlet.cs
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
This is to support https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/583)
> Add -WriteMode to Start-BqJob -Query

- Google.PowerShell.Tests/Common/GoogleApiMockExtensions.cs
- Google.PowerShell.Tests/Common/PowerShellTestBase.cs
- Google.PowerShell.Tests/Compute/AddGceInstanceCmdletTests.cs
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
This is to fix https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/586.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/588)
> Make add-gceinstance and add-gcemanagedinstancegroup throws non-terminating error

- Google.PowerShell.IntegrationTests/BigQuery/BigQuery.BqJob.Tests.ps1
- Google.PowerShell/BigQuery/BqJob.cs
This is to address https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/591)
> Remove default value for BigQuery job

- Google.PowerShell.Tests/Common/GoogleApiMockExtensions.cs
- Google.PowerShell.Tests/Provider/GoogleCloudStorageProviderTests.cs
- Google.PowerShell/Provider/CacheItem.cs
- Google.PowerShell/Provider/GoogleCloudStorageProvider.cs
> Ensure bucketCollections.CompleteAdding() is always called.

- Google.PowerShell.Tests/Compute/AddGceInstanceCmdletTests.cs
- Google.PowerShell.Tests/Compute/ManagedGceInstanceCmdletTests.cs
- Google.PowerShell.Tests/Google.PowerShell.Tests.csproj
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/598)
> Add -Region option to Get-GceManagedInstanceGroup

- Google.PowerShell.Tests/Compute/GceCmdletTestBase.cs
- Google.PowerShell.Tests/Compute/ManagedGceInstanceCmdletTests.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/599)
> Add -Region option to Remove-GceManagedInstanceGroup

- Google.PowerShell.Tests/Compute/ManagedGceInstanceCmdletTests.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
- Google.PowerShell/Compute/GoogleComputeOperationException.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/600)
> Add -Region option to Add-GceManagedInstane cmdlets

- Google.PowerShell.Tests/Compute/ManagedGceInstanceCmdletTests.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/601)
> Add support for -Region and -Name parameter for Get-GceManagedInstanceGroup

- Google.PowerShell.IntegrationTests/Compute2/Compute.GceManagedInstanceGroup.Tests.ps1
- Google.PowerShell.Tests/Compute/ManagedGceInstanceCmdletTests.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/603)
> Add -Region to Set-GceManagedInstanceGroup

- Google.PowerShell.Tests/Compute/ManagedGceInstanceCmdletTests.cs
- Google.PowerShell/Compute/GceManagedInstanceGroupCmdlets.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/604)
> Add -Region parameter to Wait-GceManagedInstanceGroup

- Google.PowerShell.Tests/Compute/AddGceInstanceCmdletTests.cs
- Google.PowerShell.Tests/Compute/AddSnapshotTests.cs
- Google.PowerShell.Tests/Compute/NewGceInstanceConfigCmdletTests.cs
- Google.PowerShell/Common/GcloudCmdlet.cs
- Google.PowerShell/Compute/GceDisk.cs
- Google.PowerShell/Compute/GceImageCmdlets.cs
- Google.PowerShell/Compute/GceInstanceCmdlets.cs
- Google.PowerShell/Compute/GceInstanceConfigCmdlets.cs
- Google.PowerShell/Compute/GceInstanceDescriptionCmdlet.cs
- Google.PowerShell/Compute/GceInstanceTemplateCmdlets.cs
- Google.PowerShell/Compute/GceSnapshotCmdlets.cs
- Google.PowerShell/Container/GkeClusterCmdlets.cs
This is to address https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-powershell/623)
> Add labels to gce cmdlets
